name: LuckPermsGUI
main: com.bghddevelopment.LuckPemsGUI.LuckPermsGUI
version: 1.0
author: Villegas21j
website: none
depend: [LuckPerms]
permissions:
  luckperms.gui:
    description: GUI LuckPerms
    default: op
commands:
   lpgui:
      description: Opens LuckPerms GUI
      usage: /<command>